### ISSUE TITLE
ArrayIndexOutOfBoundsException while rendering water world map

### ISSUE THREAD

**Issue by TOGoS** [llbit/chunky#101]
611551604 [3D Render Worker 1] ERROR se.llbit.chunky.renderer.RenderWorker  - Render worker 1 crashed with uncaught exception.
java.lang.ArrayIndexOutOfBoundsException: 2147483647
        at se.llbit.chunky.model.WaterModel.doWaterDisplacement(Unknown Source)
        at se.llbit.chunky.renderer.scene.PathTracer.pathTrace(Unknown Source)
        at se.llbit.chunky.renderer.scene.PathTracer.pathTrace(Unknown Source)
        at se.llbit.chunky.renderer.scene.PathTracer.pathTrace(Unknown Source)
        at se.llbit.chunky.renderer.scene.PathTracer.pathTrace(Unknown Source)
        at se.llbit.chunky.renderer.scene.PathTracer.pathTrace(Unknown Source)
        at se.llbit.chunky.renderer.scene.PathTracer.pathTrace(Unknown Source)
        at se.llbit.chunky.renderer.scene.PathTracer.pathTrace(Unknown Source)
        at se.llbit.chunky.renderer.scene.PathTracer.pathTrace(Unknown Source)
        at se.llbit.chunky.renderer.scene.PathTracer.pathTrace(Unknown Source)
        at se.llbit.chunky.renderer.scene.PathTracer.pathTrace(Unknown Source)
        at se.llbit.chunky.renderer.scene.Scene.pathTrace(Unknown Source)
        at se.llbit.chunky.renderer.RenderWorker.work(Unknown Source)
        at se.llbit.chunky.renderer.RenderWorker.run(Unknown Source)

This caused Chunky to stop and not render any additional passes, though otherwise the UI seemed responsive.

**Comment by llbit** [comment]
This issue was probably fixed at some point because there have not been more bug reports about it and I have not noticed any similar exceptions in the renderer in a while.
