### ISSUE TITLE
Divide by 0 error in Render Preview window

### ISSUE THREAD

**Issue by ads103** [llbit/chunky#340]
In version 1.3.6, when I attempt to drag my mouse across the Render Preview window to move my camera, I occasionally receive the following message:
```
Render worker 1 crashed with uncaught exception.
java.lang.ArithmeticException: / by zero
	at se.llbit.chunky.resources.AnimatedTexture.getColor(Unknown Source)
	at se.llbit.chunky.model.FireModel.intersect(Unknown Source)
	at se.llbit.chunky.world.Block$51.intersect(Unknown Source)
	at se.llbit.math.Octree.enterBlock(Unknown Source)
	at se.llbit.math.Octree.intersect(Unknown Source)
	at se.llbit.chunky.renderer.scene.Scene.intersect(Unknown Source)
	at se.llbit.chunky.renderer.scene.RayTracer.nextIntersection(Unknown Source)
	at se.llbit.chunky.renderer.scene.RayTracer.quickTrace(Unknown Source)
	at se.llbit.chunky.renderer.scene.Scene.quickTrace(Unknown Source)
	at se.llbit.chunky.renderer.RenderWorker.work(Unknown Source)
	at se.llbit.chunky.renderer.RenderWorker.run(Unknown Source)
```
After this worker crashes, the Preview window no longer updates. It seems to happen most frequently in especially populous scenes - lots of blocks, lots of entities.

**Comment by llbit** [comment]
Interesting, this seems like it should cause problems during regular rendering as well with anything that has a fire block in it. Thank you for the bug report!
