### ISSUE TITLE
Random NullPointerException

### ISSUE THREAD

**Issue by Masonrf** [llbit/chunky#349]
I have been getting an error every so often when trying to render a particular scene.  I'm not sure what is causing it since it has only happened on a certain scene (that I have tested at least). I am running Chunky 1.3.7 on a machine with Lubuntu 15.10 installed as the OS.  The error is as follows:

Render worker 0 crashed with uncaught exception.
java.lang.NullPointerException
	at se.llbit.chunky.model.WaterModel.intersect(Unknown Source)
	at se.llbit.chunky.world.Block$8.intersect(Unknown Source)
	at se.llbit.math.Octree.enterBlock(Unknown Source)
	at se.llbit.math.Octree.intersect(Unknown Source)
	at se.llbit.chunky.renderer.scene.Scene.intersect(Unknown Source)
	at se.llbit.chunky.renderer.scene.RayTracer.nextIntersection(Unknown Source)
	at se.llbit.chunky.renderer.scene.PathTracer.pathTrace(Unknown Source)
	at se.llbit.chunky.renderer.scene.PathTracer.pathTrace(Unknown Source)
	at se.llbit.chunky.renderer.scene.PathTracer.pathTrace(Unknown Source)
	at se.llbit.chunky.renderer.scene.Scene.pathTrace(Unknown Source)
	at se.llbit.chunky.renderer.RenderWorker.work(Unknown Source)
	at se.llbit.chunky.renderer.RenderWorker.run(Unknown Source)

Sometimes Chunky gives this error, sometimes Lubuntu gives an error and closes Chunky, and sometimes Chunky just exits with no error message from either Lubuntu or Chunky.
If this is a problem with my machine, do you know of a way I can fix it?  It has become rather annoying to have to start the render again every few hours.

**Comment by empirebuilder1** [comment]
What Java version do you have installed? Are you on a 32bit or 64bit version of Lubuntu? Try updating to the latest Oracle version (if you're using OpenJDK) by using the [WebUpd8 PPA installer](http://www.webupd8.org/2012/09/install-oracle-java-8-in-ubuntu-via-ppa.html).

**Comment by Masonrf** [comment]
java -version returns:
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)

Lubuntu is 64 bit.
To my knowledge, Java 1.8 update 66 is the newest version, and I do not remember it updating between the current render I am trying to run, and previous renders that did not have issues.

Also a test I did regarding this issue:
I updated Chunky to the 1.3.8 Alpha1 snapshot, and it also gives the same error. The only differences are that it does not give the error as often, and when something does go wrong, so far, it has only given the error instead of exiting Chunky, or freezing my computer.

**Comment by empirebuilder1** [comment]
My thoughts would be that one of the libraries might be corrupted. Delete your .chunky folder (remember to backup your renders) and run the launcher again to re-download everything required.
