### ISSUE TITLE
NullPointerException when selected chunks containing sign entity

### ISSUE THREAD

**Issue by phoenixlzx** [llbit/chunky#355]
The world save is pulled from a server with some plugins (not mods!), so there maybe something different in block storage, but can be safely ignored and treat as normal block.

If selected chunks contains those entities, the scenemanager could not load chunks correctly.

![](http://i.imgur.com/XV7ERqO.png)

(If the picture does not load, check it out here: http://i.imgur.com/XV7ERqO.png)

Debug log for this issue:

```
Settings loaded from C:\Users\Administrator\.chunky\chunky.json
Loading textures from C:\Users\Administrator\Downloads\[1.8]_R3D.CRAFT_SR-128x_v0.2.3.zip
Found Minecraft directory C:\Users\Administrator\AppData\Roaming\.minecraft
Found latest Minecraft version: C:\Users\Administrator\AppData\Roaming\.minecraft\versions\1.9\1.9.jar
Texture format error: Font texture must be 128 by 128 pixels
Failed to load textures from texture pack (C:\Users\Administrator\Downloads\[1.8]_R3D.CRAFT_SR-128x_v0.2.3.zip):
	red_sandstone_normal
	double_plant_rose_top
	double_plant_sunflower_back
	grass_path_side
	trip_wire
	dragon_egg
	log_birch
	cocoa_stage_2
	cocoa_stage_1
	cocoa_stage_0
	... plus 120 more
Failed to load textures from default texture pack (C:\Users\Administrator\AppData\Roaming\.minecraft\versions\1.9\1.9.jar):
	command_block

Saved settings to C:\Users\Administrator\.chunky\chunky.json
Settings loaded from C:\Users\Administrator\.chunky\chunky-launcher.json
Loaded 456 chunks (30672 emitters)
buffer finalization enabled
buffer finalization disabled
buffer finalization enabled
Exception in thread "Scene Manager" java.lang.NullPointerException
	at se.llbit.chunky.resources.SignTexture.<init>(Unknown Source)
	at se.llbit.chunky.world.entity.WallSignEntity.<init>(Unknown Source)
	at se.llbit.chunky.world.entity.WallSignEntity.<init>(Unknown Source)
	at se.llbit.chunky.renderer.scene.Scene.loadChunks(Unknown Source)
	at se.llbit.chunky.renderer.RenderManager.loadFreshChunks(Unknown Source)
	at se.llbit.chunky.renderer.scene.SceneManager.run(Unknown Source)
```

**Comment by llbit** [comment]
Does this bug also occur in the latest snapshot build?

**Comment by phoenixlzx** [comment]
Yes, just checked with latest snapshot.

**Comment by llbit** [comment]
I am able to reproduce the issue, with the same stack trace, and the bug has been fixed in the latest development build (not published yet). I'm working on the 1.3.8 release right now, and hopefully this will be released tomorrow at the latest.
