### ISSUE TITLE
NullPointerException on launching Chunky

### ISSUE THREAD

**Issue by ThomasRety** [llbit/chunky#386]
Hello!

I want to use chunky to render some scene of my map, but i cannot launch him.

The exceptions are as follow:

C:\Program Files (x86)\Chunky>java -jar chunky.jar
Warning: Could not load settings from C:\Program Files (x86)\Chunky\chunky.json - defaults will be used
Warning: Could not load settings from C:\Program Files (x86)\Chunky\chunky-launcher.json - defaults will be used
Exception in Application start method
Exception in thread "Thread-0" java.lang.RuntimeException: Exception in Application start method
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$155(LauncherImpl.java:182)
        at java.lang.Thread.run(Unknown Source)
Caused by: javafx.fxml.LoadException:
file:/C:/Program%20Files%20(x86)/Chunky/chunky.jar!/se/llbit/chunky/launcher/ui/ChunkyLauncher.fxml

        at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2601)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2579)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441)
        at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409)
        at se.llbit.chunky.launcher.ui.ChunkyLauncherFx.start(ChunkyLauncherFx.java:45)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$162(LauncherImpl.java:863)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(PlatformImpl.java:326)
        at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
        ... 1 more
Caused by: java.lang.NullPointerException
        at se.llbit.chunky.launcher.ui.ChunkyLauncherController.initialize(ChunkyLauncherController.java:177)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2548)
        ... 12 more

C:\Program Files (x86)\Chunky>java -version returns
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) Client VM (build 25.101-b13, mixed mode, sharing)

I'm on Windows 10 64bits. I tried reinstall Chunky but the problem persist.

Thanks for your time and your soft.

**Comment by llbit** [comment]
There is a bug in the 1.4.0 launcher (launcher version 1.9.3) causing it to crash when it could not find the Chunky settings directory. This happens for example the first time Chunky is launched.

A workaround for this issue is to use the installer for [version 1.3.8](http://chunky.llbit.se/release/1.3.8/release_notes.html) which installs an older version of the launcher that does not have this bug. Then using the launcher it is possible to upgrade to Chunky 1.4.0.
