### ISSUE TITLE
[a3] Exceptions upon changing material-settings

### ISSUE THREAD

**Issue by chland** [llbit/chunky#438]
According to your Reddit post, this shouldn' happen anymore but i just had a few minutes and tested it and 1.4.3-alpha3 still throws Exceptions when I change any of the material-settings:

```
Exception in thread "JavaFX Application Thread" java.lang.UnsupportedOperationException
	at java.util.AbstractMap.put(Unknown Source)
	at se.llbit.chunky.renderer.scene.Scene.setEmittance(Scene.java:2751)
	at se.llbit.chunky.ui.render.MaterialsTab.lambda$null$0(MaterialsTab.java:87)
	at se.llbit.chunky.ui.Adjuster.lambda$onValueChange$2(Adjuster.java:175)
        [...]
```

(( I thought it would be better to open a "real" ticket over here than to write it in the reddit-post again so things are a little bit easier to track ))

**Comment by llbit** [comment]
That is strange. I tested it before I made the alpha3 snapshot. It might have been on the wrong commit on the build machine. I tested it now in alpha4 and it seems to work. Could you give it a try in alpha4?

**Comment by chland** [comment]
Works fine in a4 :) Thanks!
