### ISSUE TITLE
Unable to launch Chunky

### ISSUE THREAD

**Issue by PuzzleMage** [llbit/chunky#462]
It's been a while since I used Chunky, and when I went to use it today the whole map was black.  I figured I needed to update it and did so.  The launcher's changed a lot, so I was probably several versions out of date.  

Now I can't get it to launch at all.  The debug console says:
Settings loaded from C:\Users\jaqi\.chunky\chunky.json
Found Minecraft directory C:\Users\jaqi\AppData\Roaming\.minecraft
Found latest Minecraft version: C:\Users\jaqi\AppData\Roaming\.minecraft\versions\17w49b\17w49b.jar
Loading 480 textures from C:\Users\jaqi\AppData\Roaming\.minecraft\versions\17w49b\17w49b.jar
Failed to load textures:
	planks_big_oak
	glass_pane_top_green
	glass_light_blue
	flower_blue_orchid
	bed_silver
	door_birch_lower
	farmland_dry
	glass_lime
	stone_diorite
	hardened_clay_stained_red
	... and 270 more
Plugins directory does not exist: C:\Users\jaqi\.chunky\plugins
Dec 07, 2017 3:15:26 PM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 8.0.65 by JavaFX runtime of version 8.0.31
Exception in Application start method
Unchecked exception caused Chunky to close.
java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(Unknown Source)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$147(Unknown Source)
	at com.sun.javafx.application.LauncherImpl$$Lambda$26/23047469.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.Error: javafx.fxml.LoadException: 
file:/C:/Users/jaqi/.chunky/lib/chunky-core-1.4.4-beta1.jar!/se/llbit/chunky/ui/SimpleColorPalette.fxml

	at se.llbit.chunky.ui.SimpleColorPalette.<init>(SimpleColorPalette.java:143)
	at se.llbit.chunky.ui.SimpleColorPicker.<init>(SimpleColorPicker.java:49)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at sun.reflect.misc.ReflectUtil.newInstance(Unknown Source)
	at javafx.fxml.FXMLLoader$InstanceDeclarationElement.constructValue(Unknown Source)
	at javafx.fxml.FXMLLoader$ValueElement.processStartElement(Unknown Source)
	at javafx.fxml.FXMLLoader.processStartElement(Unknown Source)
	at javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
	at javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
	at javafx.fxml.FXMLLoader.load(Unknown Source)
	at se.llbit.chunky.ui.ChunkyFx.start(ChunkyFx.java:38)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$153(Unknown Source)
	at com.sun.javafx.application.LauncherImpl$$Lambda$75/3584625.run(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$166(Unknown Source)
	at com.sun.javafx.application.PlatformImpl$$Lambda$71/6603281.run(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$null$164(Unknown Source)
	at com.sun.javafx.application.PlatformImpl$$Lambda$73/2210611.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$165(Unknown Source)
	at com.sun.javafx.application.PlatformImpl$$Lambda$72/1756150.run(Unknown Source)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$141(Unknown Source)
	at com.sun.glass.ui.win.WinApplication$$Lambda$63/13439768.run(Unknown Source)
	... 1 more
Caused by: javafx.fxml.LoadException: 
file:/C:/Users/jaqi/.chunky/lib/chunky-core-1.4.4-beta1.jar!/se/llbit/chunky/ui/SimpleColorPalette.fxml

	at javafx.fxml.FXMLLoader.constructLoadException(Unknown Source)
	at javafx.fxml.FXMLLoader.importClass(Unknown Source)
	at javafx.fxml.FXMLLoader.processImport(Unknown Source)
	at javafx.fxml.FXMLLoader.processProcessingInstruction(Unknown Source)
	at javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
	at javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
	at javafx.fxml.FXMLLoader.load(Unknown Source)
	at se.llbit.chunky.ui.SimpleColorPalette.<init>(SimpleColorPalette.java:134)
	... 28 more
Caused by: java.lang.ClassNotFoundException: javafx.scene.control.ButtonBar
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at javafx.fxml.FXMLLoader.loadTypeForPackage(Unknown Source)
	at javafx.fxml.FXMLLoader.loadType(Unknown Source)
	... 35 more

Chunky exited abnormally with exit value 2

Any advice?  All I want is a map.  I like chunky better than any of the other map programs I saw.  I'm on a windows machine, if that's relevant.

**Comment by PuzzleMage** [comment]
Figured I'd uninstall and reinstall it.  Uninstalled just fine, but now the download fails whenever I try to download it.

**Comment by PuzzleMage** [comment]
deleted all downloads from download folder.  Downloaded Chunky.  Installed Chunky.  Same failure to run as before.

**Comment by llbit** [comment]
It looks like you are running with a too old Java runtime. Try updating Java to the latest Java 8 release.
