### ISSUE TITLE
java.lang.NegativeArraySizeException & java.lang.ArrayIndexOutOfBoundsException when Rendering Images with "High" Resolution

### ISSUE THREAD

**Issue by stormboomer** [llbit/chunky#492]
Hi,

I'm currently trying to render Images with high resolutions and face some Issues.
When trying to render in a resolution higher than 35520x19980 the problems beginn to show up.
1. When Trying to render in 36480x20520 Chunky crashes after scene Loading with this Error
```
Loading scene took 0m 1s

Unchecked exception caused Chunky to close.
java.lang.NegativeArraySizeException
        at se.llbit.chunky.renderer.scene.Scene.initBuffers(Scene.java:366)
        at se.llbit.chunky.renderer.scene.Scene.importFromJson(Scene.java:2535)
        at se.llbit.chunky.renderer.scene.Scene.fromJson(Scene.java:2379)
        at se.llbit.chunky.renderer.scene.Scene.loadDescription(Scene.java:2501)
        at se.llbit.chunky.renderer.scene.Scene.loadScene(Scene.java:473)
        at se.llbit.chunky.renderer.scene.SynchronousSceneManager.loadScene(SynchronousSceneManager.java:146)
        at se.llbit.chunky.main.Chunky.doHeadlessRender(Chunky.java:159)
        at se.llbit.chunky.main.Chunky.main(Chunky.java:208)

Failed to launch Chunky. Command used:
/usr/lib/jvm/java-8-oracle/jre/bin/java -Xmx153600m -Dchunky.home=/home/user/.chunky -classpath /home/user/.chunky/lib/chunky-core-1.4.5.jar:/home/user/.chunky/lib/commons-math3-3.2.jar se.llbit.chunky.main.Chunky -texture /home/user/txtpack.zip -target 1 -render resolutiontest
```

2. When trying to render even Larger Images with a resolution of 61440x34560 the scene is successfull loaded, but chunky crashed while rendering with this error
```Loading octree took 0m 0s 1)
Loading regions took 0m 0s1)
Loading entities took 0m 0s)
Loading chunks: 100.0% (1,024 of 1,024)
Loading chunks took 0m 3s 1)
Finalizing octree took 0m 1s
Loading scene took 0m 13s
Rendering: 0.0% (0 of 1) [ETA=1011703407:30:07]

Render worker 1 crashed with uncaught exception.
java.lang.ArrayIndexOutOfBoundsException: 2075259000
        at se.llbit.chunky.renderer.RenderWorker.work(RenderWorker.java:135)
        at se.llbit.chunky.renderer.RenderWorker.run(RenderWorker.java:71)
```

Both Issues are showing up regardless of the Map I choose.

I'm using Chunky 1.4.5 and java version 1.8.0_181 64 Bit on a debian 9.5
Regarding the HW: I'm running a Xeon w-2145 with 256 GB ram.
If you need any more Information please let me know.

Thanks for your help.

kind regards 
Max

**Comment by marcbal** [comment]
This is because of integer overflows. An int variable can have a value between -2 147 483 648 and 2 147 483 647. When the result of a computation is outside these limits, it becomes inconsistent.

When you look at the line of code where the first exception is thrown, you can see this : 
`samples = new double[width * height * 3];`

1. With 36480 x 20520, the computation of the array's size is `36480 * 20520 * 3 = 2 245 708 800` but this result can't be stored in an integer value so the stored value is -2 049 258 496. Arrays can't have a negative size so you have the first exception.
2. With 61440 x 34560, the computed value should be 6 370 099 200 but the stored value is 2 075 131 904. This value is positive so you don't have your first error, but the program will try to access value that are not in the array, which causes the second exception.

I hope it helps you understand

**Comment by stormboomer** [comment]
Ok, I understand this. Can this be fixed in an official release?
If I remember correct double should have a max value somewhere around 1.7*10^308. 
But thanks for your effort.

**Comment by marcbal** [comment]
A floating point value can't be used as an array size, because it lost precision with high values, and it's not suitable for value indices that can't be real number, but only integer number.
Maybe a `long` value can be use for an array size (maximum value of 9 223 372 036 854 775 807) but Java doesn't support arrays with `long` index and size, only `int`.
