### ISSUE TITLE
2.0beta1 Failed to load chunk data on scene load (beta1 scene)

### ISSUE THREAD

**Issue by jackjt8** [llbit/chunky#525]
Scene created, saved, and reloaded in 2.0Beta1 fails to load and is met with a `Failed to load chunk data!` error in the console. This issue was also present in 2.0alpha builds with scenes created in those builds. Tested both a self generated 1.13.2 world and a downloaded 1.13.x world.

Example 2.0Beta .json file: [1.13_test1.txt](https://github.com/llbit/chunky/files/3224562/1.13_test1.txt)

1.4.6beta2 and previous builds can successfully save and load scenes.

- Windows 10 Home 64 bit.

---

`Failed to load chunk data!
java.io.IOException: Unrecognized block spec type: 8
    at se.llbit.chunky.chunk.BlockSpec.deserialize(BlockSpec.java:20)
    at se.llbit.chunky.chunk.BlockPalette.read(BlockPalette.java:189)
    at se.llbit.chunky.resources.OctreeFileFormat.load(OctreeFileFormat.java:44)
    at se.llbit.chunky.renderer.scene.Scene.loadOctree(Scene.java:1739)
    at se.llbit.chunky.renderer.scene.Scene.loadScene(Scene.java:505)
    at se.llbit.chunky.renderer.scene.SynchronousSceneManager.loadScene(SynchronousSceneManager.java:146)
    at se.llbit.chunky.renderer.scene.AsynchronousSceneManager.lambda$loadScene$0(AsynchronousSceneManager.java:102)
    at se.llbit.chunky.renderer.scene.AsynchronousSceneManager.run(AsynchronousSceneManager.java:81)`

**Comment by jackjt8** [comment]
[scenes.zip](https://github.com/llbit/chunky/files/3224576/scenes.zip)

[New World-.zip](https://github.com/llbit/chunky/files/3224580/New.World-.zip)

**Comment by llbit** [comment]
Saving/loading is broken right now due to a number of issues. It was not properly tested, but I'll fix it for the next beta version.

**Comment by llbit** [comment]
2.0-beta2 is now available and should fix the problem.
