### ISSUE TITLE
Chunky launch problem

### ISSUE THREAD

**Issue by Ractaros96** [llbit/chunky#549]
Hi, I'm trying to install Chunky on Ubuntu and I get this in my terminal. What does it mean?

java -jar ChunkyLauncher.jar
Exception in thread "main" java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: javafx/stage/Stage
	at se.llbit.chunky.launcher.ChunkyLauncher.firstTimeSetup(ChunkyLauncher.java:274)
	at se.llbit.chunky.launcher.ChunkyLauncher.main(ChunkyLauncher.java:192)
Caused by: java.lang.NoClassDefFoundError: javafx/stage/Stage
	... 2 more
Caused by: java.lang.ClassNotFoundException: javafx.stage.Stage
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 2 more

**Comment by leMaik** [comment]
You need to install JavaFX, `sudo apt-get install openjfx`

**Comment by Ractaros96** [comment]
> You need to install JavaFX, `sudo apt-get install openjfx`

It didn't help much. I checked again if I installed it correctly.

sudo apt-get install openjfx
[sudo] password for xxxxx: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
openjfx is already the newest version (11.0.2+1-1~18.04.2).
The following packages were automatically installed and are no longer required:
  efibootmgr libfwup1
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 5 not upgraded.

And then launched it again:

java -jar ChunkyLauncher.jar
Exception in thread "main" java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: javafx/stage/Stage
	at se.llbit.chunky.launcher.ChunkyLauncher.firstTimeSetup(ChunkyLauncher.java:274)
	at se.llbit.chunky.launcher.ChunkyLauncher.main(ChunkyLauncher.java:192)
Caused by: java.lang.NoClassDefFoundError: javafx/stage/Stage
	... 2 more
Caused by: java.lang.ClassNotFoundException: javafx.stage.Stage
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 2 more

**Comment by jackjt8** [comment]
openjfx is currently broken on Ubuntu due to it being incorrectly packaged.

Credits to Princess UNuX:

> the "easiest" way:
> 
> just run my script which should work (I didn't test it)
> https://pastebin.com/7QZgYJHW
> congratulations, now you canjust run your ChunkyLauncher.jar and it just works.
> 
> 
> the step by step way:
> 
> 1. install openjdk-8-jdk
> sudo apt install openjdk-8-jdk
> 
> 
> 2. download and install the following files:
> https://launchpadlibrarian.net/363521276/libopenjfx-jni_8u161-b12-1ubuntu2_amd64.deb
> https://launchpadlibrarian.net/363521272/libopenjfx-java_8u161-b12-1ubuntu2_all.deb
> https://launchpadlibrarian.net/363521275/openjfx_8u161-b12-1ubuntu2_amd64.deb
> 
> 
> 3. prevent ubuntu from updating openjfx
> apt-mark hold openjfx libopenjfx-java libopenjfx-jni

**Comment by Ractaros96** [comment]
It worked, thank you very much @jackjt8
