### ISSUE TITLE
ArrayIndexOutOfBoundsException from map view

### ISSUE THREAD

**Issue by jackjt8** [llbit/chunky#582]
**Versions tested:** `1.4.6-beta2`, `2.0-beta6`, `2.1-282`, `2.1-285`

**How to reproduce:** Move the Map View view port around such that new Regions or Chunks are loaded. Can also be caused by zooming in/out. `Reload`ing the map, or loading a new map does not "reset" progress towards this issue.

**Issue:** `ArrayIndexOutOfBoundsException`

In 1.X this issue can be seen to lockup the Map View while the Minimap is seen to still update with new Regions/Chunks normally.

In 2.X this issue can be seen to lockup the Map View. There is a rare occurrence where additional `ArrayIndexOutOfBoundsException`'s can be seen in the console and when this occurs the Map View can still be interacted with.

**Typical `ArrayIndexOutOfBoundsException`:**
```
Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException: 43038
	at se.llbit.chunky.map.MapBuffer.drawBuffered(MapBuffer.java:244)
	at se.llbit.chunky.ui.Map2D.repaint(Map2D.java:84)
	at se.llbit.chunky.ui.ChunkMap.repaint(ChunkMap.java:382)
	at se.llbit.chunky.ui.Map2D.lambda$repaintDeferred$0(Map2D.java:77)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$3(WinApplication.java:177)
	at java.lang.Thread.run(Thread.java:748)
``

**Comment by jackjt8** [comment]
> There is a rare occurrence where additional ArrayIndexOutOfBoundsException's can be seen in the console and when this occurs the Map View can still be interacted with.

For the following I used the Hermitcraft S6 where I zoomed out and allowed Chunky to fully load the map view. At the time of the issue was was zoomed in and was "throwing" the view around the map and I zoomed out to the biome view.

[YouTube Video from 1:45](https://youtu.be/fVUb2W6zBGg?t=104)

The full verbose console log: [error.txt](https://github.com/llbit/chunky/files/4673841/error.txt)
